// <auto-generated />
namespace TestTaskWD.Proxy
{
    internal sealed class AuthenticatedProxyClientConfiguration
        : ProxyClientConfiguration
    {
        public AuthenticatedProxyClientConfiguration(
            string apiBaseUrl,
            string apiKey)
            : base(apiBaseUrl)
        {
            this.ApiKey = apiKey;
        }

        public string ApiKey { get; set; }
    }
}
