// <auto-generated />
namespace TestTaskWD.Proxy
{
    internal interface IProxySerializer
    {
        T Deserialize<T>(byte[] source);

        byte[] Serialize<T>(T source);

        T DeserializeObject<T>(byte[] source);
    }
}