// <auto-generated />
namespace TestTaskWD.Proxy
{
    using System.Threading.Tasks;

    internal interface IProxyHttpClient
    {
        Task<byte[]> ApplyAsync(ProxyRequestDefinition definition);
    }
}