// <auto-generated />
namespace TestTaskWD.Proxy
{
    internal class ProxyClientConfiguration
    {
        public ProxyClientConfiguration(string apiBaseUrl)
        {
            this.ApiBaseUrl = apiBaseUrl;
        }

        public string ApiBaseUrl { get; set; }
    }
}
