// <auto-generated />
namespace TestTaskWD.WebApi.Services.Models
{
    using System;

    internal class ShortenUrlModel
    {
        public string ShortUrl { get; set; }

        public string FullUrl { get; set; }

        public string UrlHash { get; set; }

        public int ClickCount { get; set; }

        public DateTime CreatedOn { get; set; }
    }
}