// <auto-generated />
namespace TestTaskWD.Configuration
{
    using TestTaskWD.Configuration.Vault;

    public sealed class AppConfiguration
    {
        public ServiceConfiguration Services { get; set; } = null!;

        public VaultConfiguration Vault { get; set; } = null!;
    }
}