// <auto-generated />
namespace TestTaskWD.Configuration
{
    using System;

    public class CacheConfiguration
    {
        public TimeSpan AbsoluteExpiration { get; set; }

        public bool Enabled { get; set; }
    }
}