// <auto-generated />
namespace TestTaskWD.Configuration
{
    public class ServiceConfigurationItem
    {
        public string Uri { get; set; } = null!;

        public CacheConfiguration Cache { get; set; } = new CacheConfiguration();

        public string VaultPathApi { get; set; } = null!;
    }
}