// <auto-generated />
namespace TestTaskWD.WebApi.Services
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using TestTaskWD.WebApi.Services.Models;

    internal interface IUrlShortenerService
    {
        Task<List<ShortenUrlModel>> ShortUrlsAsync(string siteUrl, string userId, List<string> fullUrls);
    }
}