// <auto-generated />
namespace TestTaskWD.WebApi.Authentication
{
    internal class ClientProfile
    {
        public ClientProfile(string apiKey, string clientId, string displayName)
        {
            this.ApiKey = apiKey;
            this.ClientId = clientId;
            this.DisplayName = displayName;
        }

        public string ApiKey { get; }

        public string ClientId { get; }

        public string DisplayName { get; }
    }
}