// <auto-generated />
namespace TestTaskWD.WebApi.Infrastructure
{
    using TestTaskWD.WebApi.Configuration;

    public class Config
    {
        public RedisConfiguration Redis { get; set; }

        public DataBaseConfiguration DataBase { get; set; }

        public ShortUrlConfiguration Service { get; set; }

        public VaultConfig Vault { get; set; }
    }
}