// <auto-generated />
namespace TestTaskWD.Configuration.Vault
{
    public class VaultConfiguration
    {
        public const string AuthenticationSectionName = "Authentication";

        public VaultAuthenticationType AuthenticationType { get; set; }

        public VaultAuthentication Authentication { get; set; }

        public CacheConfiguration Cache { get; set; } = new CacheConfiguration();

        public VaultClientConfiguration Client { get; set; } = null!;

        public bool Enabled { get; set; }
    }
}