// <auto-generated />
namespace TestTaskWD.Session
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Http;
    using TestTaskWD.Extensions;

    internal class UserSessionMiddleware
    {
        private readonly RequestDelegate next;

        public UserSessionMiddleware(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            httpContext.Response.OnStarting(
                (state) =>
                {
                    if (string.IsNullOrEmpty(httpContext.GetUserId()))
                    {
                        httpContext.SetUserId(Guid.NewGuid().ToString());
                    }

                    return Task.CompletedTask;
                }, httpContext);

            await this.next(httpContext);
        }
    }
}