// <auto-generated />
namespace TestTaskWD.WebApi.DataAccess.Domain.Interfaces
{
    using System;

    internal interface IAuditableEntity
    {
        DateTime CreatedOn { get; set; }

        string CreatedBy { get; set; }

        DateTime EditedOn { get; set; }

        string EditedBy { get; set; }

        bool IsRemoved { get; set; }
    }
}