// <auto-generated />
namespace TestTaskWD.WebApi.Configuration
{
    public class DataBaseConfiguration
    {
        public bool IsEnabled { get; set; }

        public string ConnectionString { get; set; }

        public bool ResiliencyEnabled { get; set; }

        public int? ResiliencyCount { get; set; }

        public int? ResiliencyDelay { get; set; }
    }
}