// <auto-generated />
namespace TestTaskWD.Proxy.ShortUrlPrivateApi
{
    using System.Threading.Tasks;
    using TestTaskWD.Models;

    public interface IShortUrlClient
    {
        Task<GridOfShortenUrlModel> AddNewBatchUrlAsync(CreateNewShortUrlRequestModel request, string userGuid);

        Task<GridOfShortenUrlModel> GetUrlsAsync(
            string userGuid,
            string filterText,
            string sort,
            string sortDirection,
            int skip,
            int take);

        Task DeleteUrlAsync(string urlHash, string userGuid);

        Task<int> UpdateClickUrlAsync(string urlHash, string userGuid);
    }
}