// <auto-generated />
namespace TestTaskWD.Proxy.ShortUrlPrivateApi
{
    using System.Threading.Tasks;

    public interface IShortUrlClientFactory
    {
        Task<IShortUrlClient> CreateShortUrlClientAsync();
    }
}