// <auto-generated />
namespace TestTaskWD.Services
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using TestTaskWD.Models;

    public interface IShortUrlService
    {
        Task<GridOfShortenUrlModel> AddNewBatchUrlAsync(string userId, CreateNewShortUrlRequestModel request);

        Task<GridOfShortenUrlModel> GetUrlsAsync(
            string userId,
            string filterText,
            string sort,
            string sortDirection,
            int skip,
            int take);

        Task DeleteUrlAsync(string userId, string urlHash);

        Task<int> UpdateClickUrlAsync(string userId, string urlHash);
    }
}