// <auto-generated />
namespace TestTaskWD.WebApi.Models.V1
{
    using System.Collections.Generic;

    public sealed class CreateNewShortUrlRequestModel
    {
        public List<NewShortUrlRequestModel> FullUrls { get; set; }
    }
}