// <auto-generated />
namespace TestTaskWD.WebApi.Models.V1
{
    using System.ComponentModel.DataAnnotations;

    public class NewShortUrlRequestModel
    {
        [Url]
        [Required]
        public string Url { get; set; }
    }
}