// <auto-generated />
namespace TestTaskWD.WebApi.DataAccess.Domain.Entities
{
    using System;
    using TestTaskWD.WebApi.DataAccess.Domain.Interfaces;

    internal class ShortUrlEntity : IAuditableEntity
    {
        public string ShortUrl { get; set; }

        public string UrlHash { get; set; }

        public string FullUrl { get; set; }

        public int UrlClickCount { get; set; }

        public DateTime CreatedOn { get; set; }

        public string CreatedBy { get; set; }

        public DateTime EditedOn { get; set; }

        public string EditedBy { get; set; }

        public bool IsRemoved { get; set; }
    }
}