// <auto-generated />
namespace TestTaskWD.Extensions
{
    using System;
    using Microsoft.Extensions.Configuration;

    internal static class ConfigurationExtensions
    {
        public static TConfiguration GetConfiguration<TConfiguration>(this IConfiguration config)
        {
            var configuration = config.Get<TConfiguration>();
            if (configuration != null)
            {
                return configuration;
            }

            throw new ArgumentException(
                $"Cannot get configuration of type '{typeof(TConfiguration).Name}'",
                nameof(config));
        }
    }
}