// <auto-generated />
namespace TestTaskWD.Extensions
{
    using Microsoft.AspNetCore.Builder;
    using TestTaskWD.Antiforgery;
    using TestTaskWD.Session;

    internal static class MiddlewareExtensions
    {
        public static IApplicationBuilder UseAntiforgery(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<AntiforgeryMiddleware>();
        }

        public static IApplicationBuilder UseUserSession(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<UserSessionMiddleware>();
        }
    }
}