// <auto-generated />
namespace TestTaskWD.Extensions
{
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using TestTaskWD.Configuration;

    internal static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddConfig(
            this IServiceCollection services,
            AppConfiguration config)
        {
            return services
                .AddSingleton(config)
                .AddSingleton(config.Services)
                .AddSingleton(config.Vault);
        }

        public static IServiceCollection ConfigureVault(
            this IServiceCollection services,
            IConfiguration vaultConfigurationSection)
        {
            // TODO: realize Vault registration
            return services;
        }
    }
}