// <auto-generated />
namespace TestTaskWD.Extensions
{
    using Microsoft.AspNetCore.Http;

    internal static class SessionExtensions
    {
        public static string GetUserId(this HttpContext httpContext)
        {
            return httpContext.Session.GetString(Constants.Constants.UserIdSessionKey);
        }

        public static void SetUserId(this HttpContext httpContext, string value)
        {
            httpContext.Session.SetString(Constants.Constants.UserIdSessionKey, value);
        }
    }
}