// <auto-generated />
namespace TestTaskWD.WebApi.DataAccess.DAL
{
    using System.Threading.Tasks;
    using TestTaskWD.WebApi.DataAccess.Domain.Entities;

    internal interface IShortUrlRepository
    {
        Task<int> UpdateUrlAsync(string userId, string urlHash);

        Task DeleteUrlAsync(string userId, string urlHash);

        Task<ShortUrlEntity> AddUrlAsync(string userId, string fullUrl, string shortUrl, string urlHash);

        Task CompleteAddingAsync();
    }
}