// <auto-generated />
namespace TestTaskWD.Models
{
    public sealed class ShortUrlViewModel
    {
        public string ShortUrl { get; set; }

        public string UrlHash { get; set; }

        public string FullUrl { get; set; }

        public int UrlClickCount { get; set; }
    }
}