// <auto-generated />
namespace TestTaskWD.WebApi.Exceptions
{
    using System;

    public class ShortUrlNotFoundException : Exception
    {
        public ShortUrlNotFoundException(string userId)
            : base($"User {userId} do not have any urls")
        {
        }

        public ShortUrlNotFoundException(string userId, string urlHash)
            : base($"Url {urlHash} for user {userId} not found")
        {
        }
    }
}