// <auto-generated />
namespace TestTaskWD.Proxy.Exceptions
{
    using System;
    using System.Net;

    public sealed class RequestException : Exception
    {
        public RequestException(HttpStatusCode statusCode, string reasonPhrase, string responseContent)
            : base("An error has occurred while sending request")
        {
            this.StatusCode = statusCode;
            this.ReasonPhrase = reasonPhrase;
            this.ResponseContent = responseContent;
        }

        public HttpStatusCode StatusCode { get; }

        public string ReasonPhrase { get; }

        public string ResponseContent { get; }
    }
}