// <auto-generated />
namespace TestTaskWD.Proxy.Exceptions
{
    using System;

    public sealed class SerializationException : Exception
    {
        public SerializationException(string message, Exception innerException)
            : base(message, innerException)
        {
        }

        public SerializationException(string message, string sourceString)
            : base(message)
        {
            this.SourceString = sourceString;
        }

        public SerializationException(string message, string sourceString, Exception innerException)
            : base(message, innerException)
        {
            this.SourceString = sourceString;
        }

        public string SourceString { get; } = string.Empty;
    }
}